// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/labstack/echo/v4"
	"nifi-go/internal/app/nifigo/api"
	"nifi-go/internal/app/nifigo/server"
	"nifi-go/internal/app/nifigo/service"
	"nifi-go/internal/data"
)

// Injectors from wire.go:

// wireApp init
func wireApp() *server.HttpServer {
	echoEcho := echo.New()
	dataData := data.NewData()
	pageRepo := data.NewPageRepo(dataData)
	pageQuery := service.NewPageQuery(pageRepo)
	pageController := api.NewPageController(pageQuery)
	httpServer := server.NewHTTPServer(echoEcho, pageController)
	return httpServer
}
